[theme]

base = "light"

# Primary color (used for buttons, interactive elements)
primaryColor = "#ddf914"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for the sidebar and most interactive widgets
secondaryBackgroundColor = "#F0F2F6"

# Color used for almost all text
textColor = "#000000"

# Font settings
font = "sans serif"

# Custom fonts (requires CSS injection in your app)
[theme.fonts]
headerFont = "Lilita One, sans-serif"
bodyFont = "'Open Sans', sans-serif"


[theme.sidebar]

# Primary accent color.
#primaryColor =

# Background color of the app.
backgroundColor = "#FFFFFF"